#!/bin/sh
#
# find which process are running
#

PROGRAM=`basename $0`

if test $# -ne 1
then
    echo "Usage: $PROGRAM patten"
    exit 0
fi

ps -eo pid,cmd | grep -v $PROGRAM | grep -v grep | grep --color=auto $1
