#!/bin/bash
# By:      Sun,Shengxiang
# Created: 2012-8-31
#
# Easy compare two (files or path, path will recurse)
#
# Usage: $PROGRAM path1 path2
#

PROGRAM=$(basename $0)

if test $# -ne 2
then
	echo "Usage: $PROGRAM path1 path2"
	exit 1
fi

# rwx cmp && file type cmp
typecmp(){
	# TODO, no access cmp now
	if test ! -e "$1";then
		echo "[$1] not exist"
		exit 3
	fi
	if test ! -e "$2";then
		echo "[$2] not exist"
		exit 3
	fi
	
    local mod1=$(ls -ld $1 | awk '{print $1}' | cut -c1-4)
    local mod2=$(ls -ld $2 | awk '{print $1}' | cut -c1-4)
    if test "x$mod1" != "x$mod2";then
        echo "access mod not match [$1:$mod1], [$2:$mod2]"; exit 2
    fi
	# name
	#type1=$(file --brief "$1")
	#type2=$(file --brief "$2")
	#test "x$type1" == "x$type2"
	#if test $? -ne 0;then
	#	echo "type not match [$1],[$2]"; exit 2
	#fi
}


dircmp(){
	# $3 can disable filename cmp
	if test -z "$3"
	then
		local b1=$(basename "$1")
		local b2=$(basename "$2")
		test "x$b1" == "x$b2" || exit $?
	fi

	typecmp "$1" "$2"

	# file compare
	if test -f "$1";then 
		cmp "$1" "$2"
		if test $? -ne 0;then
			echo "[$1] [$2] file not match"; exit 4
		fi
		return
	fi

	# now dir compare, ls dir need dir executable
	if test -x "$1"
	then
		for f in $(ls -A $1) # can't manage file name that have space
		do
			local f1="$1/$f"
			local f2="$2/$f"
			dircmp "$f1" "$f2"
		done
	else
		echo "dir [$1] is not readable"; exit 5
	fi
}

dircmp "$1" "$2" first 
dircmp "$2" "$1" first
exit 0
