#!/bin/sh

IFS=' 
	'

PATH='/bin:/usr/bin:/usr/local/bin'
export PATH

prompt(){ echo "$@"; }

usage_and_exit(){
	usage
	exit $1
}

usage(){ cat <<EOF
Usage:
	$PROGRAM  [OPTIONS] folder prog

[Example]
	folder:dist have 3 files, there are 'run.sh f1 f2'
    Then use cmd
    $PROGRAM dist run.sh
	the run.sh is the start script
    there is file run.sh generate in current dir
...
EOF
}

version(){ echo "version $VERSION"; }
error(){
	echo "ERROR:" "$@"
	exit 1
}

PROGRAM=`basename $0`
VERSION="1.1"
HEADERFILE=`dirname $0`/header.sh

curdir="$(cd $(dirname $0); pwd)"
location=
while test $# -ne 0
do
	case $1 in 
	--temp)
		location='mktemp'
		;;
	-v|--version)
		version
		exit
		;;
	-h|--help)
		usage_and_exit 0
		;;
	-*)
		error "Unknown option $1"
		;;
	*)
		break
		;;
	esac
	shift
done

prompt "check environment ..."
test $# -ne 2 && usage_and_exit 1
source=$1
test -d $source || error "source must be directory"
script=$2
target=$2
test -f $source/$script || error "script must be a file"
tmpdir=`mktemp -d`
trap '/bin/rm -r $tmpdir' EXIT

prompt "start to make ..."
prompt "create package"
cd $source
tar -czf $tmpdir/dist.tar.gz *
cd $OLDPWD

pwd
prompt "add header"
cat $curdir/header.sh $tmpdir/dist.tar.gz > $PWD/$target

prompt "add execute attribute"
chmod +x $target

prompt "finish make, generate file $target"

